#!/usr/bin/env node
// Reads the monorepo root .env and writes apps/extension/.env.local with
// ONLY the two WXT_-prefixed vars the extension is allowed to read at build
// time (see ../lib/supabase.ts). Never copies the service-role key or any
// other secret — Vite/WXT bundles whatever lands in .env.local straight
// into the built extension's client-side JS, so this is the one deliberate
// narrowing point between "everything in the root .env" and "what ships in
// a Chrome extension."
//
// Wired as a predev/prebuild hook (see package.json) so `wxt`/`wxt build`
// always see a fresh .env.local; safe to run standalone too:
//   node scripts/sync-env.mjs

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_ENV_PATH = path.resolve(__dirname, "../../../.env");
const OUT_PATH = path.resolve(__dirname, "../.env.local");

/**
 * Minimal KEY=VALUE parser matching this repo's .env style (see
 * .env.example): `#`-comment lines and blank lines are skipped, and a value
 * may carry a trailing ` # comment` (e.g. `STRIPE_PRICE_MONTHLY=price_123 #
 * $4/mo price id`) which is stripped. Not a general-purpose dotenv parser —
 * no quoting/escaping support, matching every .env in this repo today.
 */
function parseEnv(text) {
  const values = {};
  for (const rawLine of text.split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1);
    const commentIdx = value.indexOf(" #");
    if (commentIdx !== -1) value = value.slice(0, commentIdx);
    values[key] = value.trim();
  }
  return values;
}

function main() {
  if (!fs.existsSync(ROOT_ENV_PATH)) {
    // No root .env at all (fresh clone, no cloud setup yet) — write nothing
    // rather than a .env.local with two blank keys. getClient() (lib/
    // supabase.ts) treats a missing .env.local exactly the same as one with
    // empty values: cloud features render a quiet "not configured" state.
    console.log("[sync-env] no root .env found; skipping (extension builds fine without cloud config)");
    return;
  }

  const values = parseEnv(fs.readFileSync(ROOT_ENV_PATH, "utf8"));
  const url = values.SUPABASE_URL ?? "";
  const anonKey = values.SUPABASE_ANON_KEY ?? "";

  const out = `# Generated by scripts/sync-env.mjs from the root .env — DO NOT EDIT BY HAND
# and DO NOT COMMIT (gitignored via the repo-wide ".env.*" pattern). Only the
# two vars the extension is allowed to read at build time; never the
# service-role key or any other secret from the root .env.
WXT_SUPABASE_URL=${url}
WXT_SUPABASE_ANON_KEY=${anonKey}
`;
  fs.writeFileSync(OUT_PATH, out);
  console.log(
    `[sync-env] wrote ${path.relative(process.cwd(), OUT_PATH)} (${
      url && anonKey ? "cloud configured" : "no cloud config — auth UI will show 'not configured'"
    })`,
  );
}

main();
