#!/usr/bin/env node
// Reads the monorepo root .env and writes apps/extension/.env.local with
// ONLY the WXT_-prefixed vars the extension is allowed to read at build
// time (see ../lib/supabase.ts, ../lib/share-url.ts). Never copies the
// service-role key or any other secret — Vite/WXT bundles whatever lands in
// .env.local straight into the built extension's client-side JS, so this is
// the one deliberate narrowing point between "everything in the root .env"
// and "what ships in a Chrome extension." WXT_SITE_URL is the one exception
// to "secret-free build config" — it's the PUBLIC web app origin (same
// value apps/web itself reads as NEXT_PUBLIC_SITE_URL), never a secret, and
// is what ShareDialog's `shareUrlFor` (lib/share-url.ts) builds
// `<site>/s/<slug>` links from. It has a public-facing fallback
// (https://tabburrow.com) so a build with no root .env at all still
// produces a real, resolvable share URL shape rather than an empty prefix.
//
// Wired as a predev/prebuild hook (see package.json) so `wxt`/`wxt build`
// always see a fresh .env.local; safe to run standalone too:
//   node scripts/sync-env.mjs

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_ENV_PATH = path.resolve(__dirname, "../../../.env");
const OUT_PATH = path.resolve(__dirname, "../.env.local");

/**
 * Minimal KEY=VALUE parser matching this repo's .env style (see
 * .env.example): `#`-comment lines and blank lines are skipped, and a value
 * may carry a trailing ` # comment` (e.g. `STRIPE_PRICE_MONTHLY=price_123 #
 * $4/mo price id`) which is stripped. Not a general-purpose dotenv parser —
 * no quoting/escaping support, matching every .env in this repo today.
 */
function parseEnv(text) {
  const values = {};
  for (const rawLine of text.split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1);
    const commentIdx = value.indexOf(" #");
    if (commentIdx !== -1) value = value.slice(0, commentIdx);
    values[key] = value.trim();
  }
  return values;
}

// Same literal fallback `lib/share-url.ts`'s `shareUrlFor` defends with —
// duplicated by hand rather than imported (this is a plain Node script, that
// is TS bundled by WXT/Vite; same "kept in sync by hand across runtimes"
// precedent e2e/env.ts's docstring already sets for this repo's other
// duplicated env-parsing logic). If these two ever drift, the WORST case is
// a build-time URL that still resolves to a real (if wrong) TabBurrow
// origin, never a broken link — see share-url.ts's own defensive fallback.
const DEFAULT_SITE_URL = "https://tabburrow.com";

function main() {
  const rootEnvExists = fs.existsSync(ROOT_ENV_PATH);
  // No root .env at all (fresh clone, no cloud setup yet) is NOT a reason to
  // skip writing .env.local anymore: WXT_SITE_URL has a public-facing
  // fallback and doesn't depend on any secret, so a build with zero cloud
  // config should still get a real (if generic) share-URL origin instead of
  // an unset var. Supabase's two vars stay blank in that case, exactly as
  // before — getClient() (lib/supabase.ts) treats blank the same as absent.
  const values = rootEnvExists ? parseEnv(fs.readFileSync(ROOT_ENV_PATH, "utf8")) : {};
  const url = values.SUPABASE_URL ?? "";
  const anonKey = values.SUPABASE_ANON_KEY ?? "";
  const siteUrl = (values.NEXT_PUBLIC_SITE_URL ?? "").trim() || DEFAULT_SITE_URL;

  const out = `# Generated by scripts/sync-env.mjs from the root .env — DO NOT EDIT BY HAND
# and DO NOT COMMIT (gitignored via the repo-wide ".env.*" pattern). Only the
# vars the extension is allowed to read at build time; never the
# service-role key or any other secret from the root .env.
WXT_SUPABASE_URL=${url}
WXT_SUPABASE_ANON_KEY=${anonKey}
WXT_SITE_URL=${siteUrl}
`;
  fs.writeFileSync(OUT_PATH, out);
  console.log(
    `[sync-env] wrote ${path.relative(process.cwd(), OUT_PATH)} (${
      url && anonKey ? "cloud configured" : "no cloud config — auth UI will show 'not configured'"
    }; site=${siteUrl}${rootEnvExists ? "" : ", no root .env found"})`,
  );
}

main();
