import "server-only";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

/**
 * Server-only data access for public share pages (`app/s/[slug]`). This is
 * the sanctioned alternative to a share-resolve Edge Function (see
 * docs/plans/2026-07-15-tabburrow-build.md, Task 21): `collections`/`links`
 * RLS is owner-only (supabase/migrations/0001_init.sql), so an anonymous
 * visitor can only ever see shared data through this module, which reads
 * with the service role and hand-picks exactly the columns a public page is
 * allowed to show. The `server-only` import above makes any accidental
 * Client Component import of this file a build-time error, so the service
 * role key can never reach a client bundle.
 */

/** One link on a shared collection page. Never includes an id, collection id, or user id. */
export interface SharedLink {
  url: string;
  title: string;
  faviconUrl: string | null;
  note: string | null;
  tags: string[];
}

export interface SharedCollection {
  collection: {
    name: string;
    /** A CSS color value (`var(...)`/`color-mix(...)`/`#hex`) or an emoji glyph; see `isCssColorAccent`. */
    accent: string | null;
    allowIndex: boolean;
  };
  links: SharedLink[];
}

/**
 * Share slugs are generated by the extension's share toggle (T22, not yet
 * built) with `nanoid(10)` restricted to a lowercase-alphanumeric alphabet
 * (see the plan's Task 22 interface note). Validating the shape BEFORE ever
 * building a query means a malformed slug (wrong length, uppercase,
 * punctuation) short-circuits to "not found" without touching the database.
 */
const SHARE_SLUG_PATTERN = /^[a-z0-9]{10}$/;

export function isValidShareSlug(slug: string): boolean {
  return SHARE_SLUG_PATTERN.test(slug);
}

/**
 * Plain lexicographic string sort. `links.position` is a base-62
 * fractional-index key (packages/core/src/fractional-index.ts) whose
 * alphabet is defined in ASCII order (digits < uppercase < lowercase), so
 * ordinary `<`/`>` string comparison already sorts correctly, matching the
 * same ordering the extension's Dexie index uses. No numeric parsing.
 */
export function sortByPosition<T extends { position: string }>(rows: readonly T[]): T[] {
  return [...rows].sort((a, b) => (a.position < b.position ? -1 : a.position > b.position ? 1 : 0));
}

/** Hostname for a link URL, or null when the stored URL doesn't parse. */
export function faviconHost(url: string): string | null {
  try {
    return new URL(url).hostname;
  } catch {
    return null;
  }
}

/** The only schemes a shared link may be rendered as a real, clickable href. */
const LINKABLE_PROTOCOLS = new Set(["http:", "https:"]);

/** A URL's protocol (e.g. "https:"), or null when it isn't an absolute URL at all. */
function protocolOf(url: string): string | null {
  try {
    return new URL(url).protocol;
  } catch {
    return null;
  }
}

/**
 * The href to render for a stored link URL on the PUBLIC share page, or null
 * when that URL must not become a link.
 *
 * This is a security boundary, not a formatting helper. A shared collection's
 * URLs are attacker-controlled in the relevant sense: anyone can type
 * arbitrary text into the extension's "+ Add link" field (its `type="url"` is
 * inert — the inputs aren't inside a `<form>`, so constraint validation never
 * runs), or import arbitrary JSON, then share that collection publicly. Piping
 * such a string straight into `<a href>` makes a saved `javascript:…` "link"
 * execute on this origin the moment a visitor clicks it — stored XSS. So the
 * scheme is allowlisted to http/https rather than blocklisted: `javascript:`
 * is merely the obvious one, and `data:`/`vbscript:`/`blob:` are no better.
 *
 * Note the extension itself was never exposed to this — it opens links with
 * `chrome.tabs.create`, which refuses `javascript:` URLs. Only this web page
 * renders them as hrefs.
 *
 * A SCHEMELESS url ("nike.com") is upgraded to https rather than rejected:
 * as an href it would otherwise resolve relative to this page
 * (tabburrow.com/s/<slug>/nike.com) and 404. That mirrors what `normalizeUrl`
 * does in `@tabburrow/core` for the extension (issue #24); it's re-derived
 * here rather than imported because `apps/web` doesn't depend on that package,
 * and adding the dependency to reach one pure function would pull Dexie into
 * the Next.js bundle — the same "local copy beats a shared package for one
 * small pure helper" call `isCssColorAccent` below already made.
 */
export function safeLinkHref(rawUrl: string): string | null {
  const url = rawUrl.trim();
  if (!url) return null;

  const protocol = protocolOf(url);
  if (protocol !== null) return LINKABLE_PROTOCOLS.has(protocol) ? url : null;

  // Not absolute — try it as a bare domain. The result is re-checked through
  // the same allowlist rather than trusted, so this can't become a bypass.
  const prefixed = `https://${url}`;
  const prefixedProtocol = protocolOf(prefixed);
  return prefixedProtocol !== null && LINKABLE_PROTOCOLS.has(prefixedProtocol) ? prefixed : null;
}

/**
 * Favicon image source for a link row. Prefers the favicon the extension
 * captured at save time (chrome's `_favicon` API is a browser-extension-only
 * surface with no web equivalent, so this server-rendered page can never
 * capture one itself). Links without a stored favicon fall back to Google's
 * public s2 favicon service, keyed by hostname. Returns null only when the
 * URL can't be parsed into a hostname either, in which case the favicon slot
 * renders blank rather than a broken image.
 */
export function resolveFaviconSrc(link: { url: string; faviconUrl: string | null }): string | null {
  if (link.faviconUrl) return link.faviconUrl;
  const host = faviconHost(link.url);
  return host ? `https://www.google.com/s2/favicons?domain=${host}&sz=32` : null;
}

/** Truncates to at most `maxLength` characters, appending a single ellipsis character when cut. */
export function truncate(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return `${text.slice(0, Math.max(0, maxLength - 1))}…`;
}

/**
 * True when `accent` is a CSS color value (renders as a colored dot) rather
 * than an emoji/text glyph (renders as a character). Duplicated from
 * apps/extension/lib/accents.ts's `isCssColorAccent` (that file lives in a
 * private app, not a published package apps/web can import; it's a two-line
 * pure function, so a local copy is simpler than adding a shared package for
 * one helper (same precedent as apps/web/lib/cx.ts, which duplicates
 * packages/ui's internal `cx`).
 */
export function isCssColorAccent(accent: string): boolean {
  return accent.startsWith("var(") || accent.startsWith("color-mix(") || accent.startsWith("#");
}

function hasShareEnv(): boolean {
  return Boolean(process.env.SUPABASE_URL?.trim() && process.env.SUPABASE_SERVICE_ROLE_KEY?.trim());
}

// Sentinel distinguishes "not yet computed" (undefined) from "computed and
// genuinely unconfigured" (null), mirroring apps/extension/lib/supabase.ts's
// getClient() memoization.
let _client: SupabaseClient | null | undefined;

/**
 * Service-role Supabase client, memoized per server process. `null` when
 * `SUPABASE_URL`/`SUPABASE_SERVICE_ROLE_KEY` aren't set (self-hosters who
 * haven't configured cloud features yet, per SELF_HOSTING.md): share pages
 * just resolve to "not found" in that case (see `getSharedCollection`)
 * rather than crashing; local-only self-hosting is a fully supported mode.
 * `persistSession: false` because this client is created fresh per request
 * on the server and never needs to remember a session between calls.
 */
function getServiceRoleClient(): SupabaseClient | null {
  if (_client !== undefined) return _client;
  if (!hasShareEnv()) {
    _client = null;
    return _client;
  }
  _client = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, {
    auth: { persistSession: false },
  });
  return _client;
}

interface CollectionRow {
  id: string;
  name: string;
  accent: string | null;
  allow_index: boolean;
}

interface LinkRow {
  url: string;
  title: string;
  favicon_url: string | null;
  note: string | null;
  tags: string[] | null;
  position: string;
}

/**
 * Resolves a public share slug to its collection and live (non-tombstoned)
 * links, or `null` when the slug is malformed, unknown, unshared, or the
 * collection is soft-deleted. Callers (the share page and its OG image
 * route) must treat `null` as "render a 404": never fall back to any
 * partial data.
 *
 * Caching: the page calling this sets `export const revalidate = 60` (ISR),
 * so a collection unshared from the extension can remain visible here for
 * up to 60 seconds after that change syncs to Supabase. That's the honest
 * shape of "propagates within one sync cycle" for a statically-rendered
 * page with no realtime subscription to the share table; documented here
 * rather than promising instant unshare.
 */
export async function getSharedCollection(slug: string): Promise<SharedCollection | null> {
  if (!isValidShareSlug(slug)) return null;

  const supabase = getServiceRoleClient();
  if (!supabase) return null;

  const { data: collection, error: collectionError } = await supabase
    .from("collections")
    .select("id, name, accent, allow_index")
    .eq("share_slug", slug)
    .eq("is_shared", true)
    .is("deleted_at", null)
    .maybeSingle<CollectionRow>();

  if (collectionError || !collection) return null;

  const { data: links, error: linksError } = await supabase
    .from("links")
    .select("url, title, favicon_url, note, tags, position")
    .eq("collection_id", collection.id)
    .is("deleted_at", null)
    .returns<LinkRow[]>();

  // Fail closed: a query error on the links half means we don't actually
  // know what's live, so don't render the collection with a possibly-wrong
  // (empty or stale) link list.
  if (linksError) return null;

  const sharedLinks: SharedLink[] = sortByPosition(links ?? []).map((link) => ({
    url: link.url,
    title: link.title,
    faviconUrl: link.favicon_url,
    note: link.note,
    tags: link.tags ?? [],
  }));

  return {
    collection: {
      name: collection.name,
      accent: collection.accent,
      allowIndex: collection.allow_index,
    },
    links: sharedLinks,
  };
}
